# =============================================================================
# Sr. Barbara's Class — build_game.py
# Assembles dist/sr_barbara.html from source files.
#
# Usage:
#   srb-build
#
# Reads:  sr_barbara.yaml (via ProjectConfig)
#         data/game_config.yaml
#         data/sentences.yaml
#         templates/index.standalone.html
#         static/css/style.css
#         static/js/layout.js, renderer.js, ui.js, main.js
#         static/images/sr_barbara.png
#         pyproject.toml (version)
# Writes: dist/sr_barbara.html
# =============================================================================

import base64
import json
import tomllib
from pathlib import Path

import yaml

from sr_barbara_scripts.config import ProjectConfig


# -----------------------------------------------------------------------------
# ConfigRenderer
# Reads game_config.yaml and renders the contents of config.js as a string.
# Also reads the full version from pyproject.toml and injects VERSION and
# GITHUB_REPO constants used by the update checker.
# -----------------------------------------------------------------------------

class ConfigRenderer:
    """Renders config.js content from game_config.yaml and pyproject.toml."""

    def __init__(self, config: ProjectConfig):
        self._cfg     = config
        self._game    = self._load_game_config()
        self._version = self._read_full_version()

    def _load_game_config(self) -> dict:
        path = self._cfg.repo_root / 'data' / 'game_config.yaml'
        with path.open(encoding='utf-8') as f:
            return yaml.safe_load(f)

    def _read_full_version(self) -> str:
        """Read the full major.minor.patch version from pyproject.toml."""
        toml_path = self._cfg.repo_root / 'pyproject.toml'
        with toml_path.open('rb') as f:
            data = tomllib.load(f)
        return data['project']['version']

    def render(self) -> str:
        """Return the full config.js content as a string."""
        c = self._game['canvas']
        d = self._game['dialogue']
        p = self._game['pos']

        end_x = c['width'] - 20  # derived, not stored in config

        lines = [
            '// Generated by srb-build — do not edit.',
            '// Source of truth: data/game_config.yaml and pyproject.toml',
            '',
            '// Build version — used by the update checker',
            f'const VERSION = "{self._version}";',
            '',
            '// GitHub repo — used by the update checker',
            'const GITHUB_REPO = "carolynboyle/sr-barbara";',
            '',
            '// Canvas dimensions',
            f"const W        = {c['width']};",
            f"const H        = {c['height']};",
            f"const BASE_Y   = {c['base_y']};",
            f"const START_X  = {c['start_x']};",
            f"const END_X    = {end_x};",
            f"const MARGIN   = {c['margin']};",
            '',
            '// Font size cascade — try each in order until text fits',
            f"const FONT_SIZES = {json.dumps(c['font_sizes'])};",
            f"const MIN_FONT   = {c['min_font']};",
            '',
            "// Sr. Barbara's dialogue",
            f'const PRAISE = {json.dumps(d["praise"], ensure_ascii=False, indent=4)};',
            '',
            f'const SCOLD = {json.dumps(d["scold"], ensure_ascii=False, indent=4)};',
            '',
            '// Part of speech colors — muted, chalkboard-friendly',
            'const POS_COLORS = ' + json.dumps(p['colors'], ensure_ascii=False, indent=4) + ';',
            '',
            'const POS_LABELS = ' + json.dumps(p['labels'], ensure_ascii=False, indent=4) + ';',
        ]
        return '\n'.join(lines)


# -----------------------------------------------------------------------------
# DataRenderer
# Reads sentences.yaml and renders data.standalone.js as a string.
# Replaces the fetch('/api/sentence') call with a local SENTENCES lookup.
# Token IDs are synthesized sequentially since YAML has no Postgres row IDs.
# -----------------------------------------------------------------------------

class DataRenderer:
    """Renders data.standalone.js content from sentences.yaml."""

    def __init__(self, config: ProjectConfig):
        self._cfg       = config
        self._sentences = self._load_sentences()

    def _load_sentences(self) -> list:
        path = self._cfg.repo_root / self._cfg.paths['sentences_yaml']
        with path.open(encoding='utf-8') as f:
            data = yaml.safe_load(f)
        return data['sentences']

    def _build_tokens(self, sentence: dict) -> list:
        """
        Flatten phrase/token structure into a token list matching the
        shape the Flask API returns. Synthesizes sequential token IDs
        since YAML does not store Postgres row IDs.
        """
        tokens = []
        token_id = 1
        for part_position, phrase in enumerate(sentence['phrases'], start=1):
            for token in phrase['tokens']:
                tokens.append({
                    'id':            token_id,
                    'word':          token['word'],
                    'pos':           token['pos'],
                    'part_role':     phrase['role'],
                    'part_position': part_position,
                })
                token_id += 1
        return tokens

    def _build_sentence_text(self, tokens: list) -> str:
        return ' '.join(t['word'] for t in tokens)

    def render(self) -> str:
        """Return the full data.standalone.js content as a string."""
        records = []
        for sentence in self._sentences:
            tokens = self._build_tokens(sentence)
            records.append({
                'id':         sentence['id'],
                'difficulty': sentence['difficulty'],
                'sentence':   self._build_sentence_text(tokens),
                'tokens':     tokens,
            })

        sentences_json = json.dumps(records, ensure_ascii=False, indent=2)

        lines = [
            '// Generated by srb-build — do not edit.',
            '// Source of truth: data/sentences.yaml',
            '',
            f'const SENTENCES = {sentences_json};',
            '',
            '// Replaces fetch(\'/api/sentence\') for the standalone build.',
            '// Identical call signature to data.js so main.js is unchanged.',
            'function fetchSentence() {',
            '    const difficulty = difficultySelect.value;',
            '    sentenceDisplay.textContent = \'Loading…\';',
            '    hidePopup();',
            '    feedbackBar.classList.add(\'hidden\');',
            '',
            '    const pool = difficulty === \'any\'',
            '        ? SENTENCES',
            '        : SENTENCES.filter(s => s.difficulty === difficulty);',
            '',
            '    if (pool.length === 0) {',
            '        sentenceDisplay.textContent = \'No sentence found for that difficulty.\';',
            '        return;',
            '    }',
            '',
            '    const data = pool[Math.floor(Math.random() * pool.length)];',
            '    currentSentence = data;',
            '    renderSentence(data);',
            '    initDiagram();',
            '}',
        ]
        return '\n'.join(lines)


# -----------------------------------------------------------------------------
# GameBuilder
# Orchestrates the build: reads all source files, calls the renderers,
# inlines everything into index.standalone.html, writes the output file.
# -----------------------------------------------------------------------------

class GameBuilder:
    """Assembles dist/sr_barbara.html from source files and rendered content."""

    def __init__(self, config: ProjectConfig):
        self._cfg             = config
        self._config_renderer = ConfigRenderer(config)
        self._data_renderer   = DataRenderer(config)

    def _read(self, path: Path) -> str:
        return path.read_text(encoding='utf-8')

    def _inline_css(self) -> str:
        css_path = self._cfg.repo_root / 'static' / 'css' / 'style.css'
        return f'<style>\n{self._read(css_path)}\n</style>'

    def _inline_scripts(self) -> str:
        blocks = []

        # 1. config.js — generated from game_config.yaml + pyproject.toml version
        blocks.append(
            f'<script>\n{self._config_renderer.render()}\n</script>'
        )

        # 2. layout.js, renderer.js, ui.js — read as-is
        js_dir = self._cfg.repo_root / 'static' / 'js'
        for filename in ['layout.js', 'renderer.js', 'ui.js']:
            content = self._read(js_dir / filename)
            blocks.append(f'<script>\n{content}\n</script>')

        # 3. data.standalone.js — generated from sentences.yaml
        blocks.append(
            f'<script>\n{self._data_renderer.render()}\n</script>'
        )

        # 4. main.js — read as-is (must be last)
        content = self._read(js_dir / 'main.js')
        blocks.append(f'<script>\n{content}\n</script>')

        return '\n\n'.join(blocks)

    def _inline_image(self) -> str:
        img_path = self._cfg.repo_root / 'static' / 'images' / 'sr_barbara.png'
        raw = img_path.read_bytes()
        b64 = base64.b64encode(raw).decode('ascii')
        return f'data:image/png;base64,{b64}'

    def build(self) -> None:
        """Run the build and write the output HTML file."""
        root          = self._cfg.repo_root
        template_path = root / self._cfg.paths['standalone_template']
        output_path   = root / self._cfg.paths['build_output']

        template = self._read(template_path)

        output = template
        output = output.replace('<!-- INLINE_CSS -->',     self._inline_css())
        output = output.replace('<!-- INLINE_SCRIPTS -->', self._inline_scripts())
        output = output.replace('{{ IMAGE_SRC }}',         self._inline_image())

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(output, encoding='utf-8')

        size_kb = output_path.stat().st_size / 1024
        version = self._config_renderer._version
        print(f'Built {output_path} ({size_kb:.0f} KB) — version {version}')


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------

def main():
    # Repo root is three levels up from this file:
    # scripts/src/sr_barbara_scripts/build_game.py
    repo_root = Path(__file__).resolve().parents[3]

    config  = ProjectConfig(repo_root)
    builder = GameBuilder(config)
    builder.build()


if __name__ == '__main__':
    main()
