# =============================================================================
# Sr. Barbara's Class — pg_export.py
# Exports sentence data from Postgres to data/sentences.yaml.
#
# Usage:
#   srb-export
#
# Reads:  sr_barbara.yaml (via ProjectConfig)
#         data/queries.yaml (via ProjectConfig)
#         pyproject.toml (via ProjectConfig)
#         .env (database credentials)
# Writes: data/sentences.yaml
# =============================================================================

import os
from pathlib import Path

import psycopg2
import yaml
from dotenv import load_dotenv

from sr_barbara_scripts.config import ProjectConfig


# -----------------------------------------------------------------------------
# Exporter
# -----------------------------------------------------------------------------

class SentenceExporter:
    """Connects to Postgres and exports all sentences to sentences.yaml."""

    # Difficulty sort order for output grouping
    DIFFICULTY_ORDER = {'easy': 0, 'medium': 1, 'hard': 2}

    def __init__(self, config: ProjectConfig):
        self.config = config
        self.conn   = self._connect()

    def _connect(self) -> psycopg2.extensions.connection:
        env_file = self.config.repo_root / self.config.database['env_file']
        load_dotenv(env_file)
        return psycopg2.connect(
            host=self.config.database['host'],
            port=self.config.database['port'],
            database=os.getenv('DB_NAME'),
            user=os.getenv('DB_USER'),
            password=os.getenv('DB_PASSWORD'),
        )

    def _fetch_sentences(self) -> list:
        """Query all sentences with their parts and tokens."""
        cur = self.conn.cursor()
        cur.execute(self.config.queries['export']['fetch_sentences'])
        rows = cur.fetchall()
        cur.close()
        return rows

    def _build_data(self, rows: list) -> list:
        """Assemble flat query rows into nested sentence/phrase/token structure."""
        sentences = {}

        for row in rows:
            (sentence_id, difficulty, part_role, part_position,
             token_id, word, token_pos, token_position) = row

            if sentence_id not in sentences:
                sentences[sentence_id] = {
                    'id':         sentence_id,
                    'difficulty': difficulty,
                    'phrases':    {},
                }

            phrase_key = part_position
            if phrase_key not in sentences[sentence_id]['phrases']:
                sentences[sentence_id]['phrases'][phrase_key] = {
                    'role':   part_role,
                    'tokens': [],
                }

            sentences[sentence_id]['phrases'][phrase_key]['tokens'].append({
                'word': word,
                'pos':  token_pos,
            })

        # Convert to sorted list — easy → medium → hard, then by id
        result = []
        for sentence in sorted(
            sentences.values(),
            key=lambda s: (self.DIFFICULTY_ORDER.get(s['difficulty'], 99), s['id'])
        ):
            result.append({
                'id':         sentence['id'],
                'difficulty': sentence['difficulty'],
                'phrases':    list(sentence['phrases'].values()),
            })

        return result

    def export(self) -> None:
        """Run the export and write sentences.yaml."""
        rows      = self._fetch_sentences()
        sentences = self._build_data(rows)

        output_path = self.config.repo_root / self.config.paths['sentences_yaml']
        output_path.parent.mkdir(parents=True, exist_ok=True)

        header = (
            f"# Generated by srb-export v{self.config.version}"
            f" — do not edit by hand.\n"
            f"# Re-run srb-export to regenerate from Postgres.\n"
        )

        with output_path.open('w', encoding='utf-8') as f:
            f.write(header)
            f.write('\n')
            yaml.dump(
                {'sentences': sentences},
                f,
                allow_unicode=True,
                default_flow_style=False,
                sort_keys=False,
            )

        print(f"Exported {len(sentences)} sentences to {output_path}")

    def close(self) -> None:
        """Close the database connection."""
        if self.conn and not self.conn.closed:
            self.conn.close()


# -----------------------------------------------------------------------------
# Entry point
# -----------------------------------------------------------------------------

def main():
    # Repo root is three levels up from this file:
    # scripts/src/sr_barbara_scripts/pg_export.py
    repo_root = Path(__file__).resolve().parents[3]

    config   = ProjectConfig(repo_root)
    exporter = SentenceExporter(config)
    try:
        exporter.export()
    finally:
        exporter.close()


if __name__ == '__main__':
    main()
