services:
  db:
    image: docker.io/postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sr_barbara
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: srbarbaradb
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
      - ./db/sentences_view.sql:/docker-entrypoint-initdb.d/03-sentences_view.sql
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_NAME: sr_barbara
      DB_USER: postgres
      DB_PASSWORD: srbarbaradb
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
