#!/usr/bin/env bash
# =============================================================================
# Sr. Barbara's Class — repo reorganization script
#
# Run from the repo root:
#   bash docs/changedocs/reorganize.sh
#
# What this does:
#   - Creates new directory structure
#   - Moves files to their new locations
#   - Archives superseded scripts
#   - Removes generated artifacts that belong in .gitignore
#
# What this does NOT do:
#   - Delete anything permanently (archived items go to docs/archive/)
#   - Create new source files (pg_export.py, build_slingcode.py, etc.)
#   - Modify any file contents
#
# Review carefully before running. Run once from a clean git state so
# you can revert with: git checkout -- .
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

echo "Working in: $REPO_ROOT"
echo ""

# -----------------------------------------------------------------------------
# Step 1: Create new directories
# -----------------------------------------------------------------------------

echo "[1/7] Creating new directories..."

mkdir -p data
mkdir -p dist
mkdir -p docs/archive
mkdir -p scripts/src/sr_barbara_scripts
mkdir -p docs/changedocs
mkdir -p docs/design

echo "      done."

# -----------------------------------------------------------------------------
# Step 2: Move docs into subdirectories
# -----------------------------------------------------------------------------

echo "[2/7] Reorganizing docs/..."

# Design documents
[ -f docs/sr-barbara-schema-analysis.md ] && \
    mv docs/sr-barbara-schema-analysis.md docs/design/sr-barbara-schema-analysis.md

# Consolidate roadmaps — keep the newer one, archive the dated one
[ -f "docs/roadmap 2026-02-27 22.41.39.md" ] && \
    mv "docs/roadmap 2026-02-27 22.41.39.md" docs/archive/roadmap-2026-02-27.md

# Change documents (may already be in changedocs from earlier work)
[ -f docs/game-js-pp-fix.md ] && \
    mv docs/game-js-pp-fix.md docs/changedocs/game-js-pp-fix.md
[ -f docs/sr-barbara-docker-changes.md ] && \
    mv docs/sr-barbara-docker-changes.md docs/changedocs/sr-barbara-docker-changes.md

echo "      done."

# -----------------------------------------------------------------------------
# Step 3: Archive superseded scripts
# -----------------------------------------------------------------------------

echo "[3/7] Archiving superseded scripts..."

[ -f scripts/run_local.sh ] && \
    mv scripts/run_local.sh docs/archive/run_local.sh
[ -f scripts/setup.py ] && \
    mv scripts/setup.py docs/archive/setup.py

echo "      done."

# -----------------------------------------------------------------------------
# Step 4: Create scripts src layout placeholder files
# -----------------------------------------------------------------------------

echo "[4/7] Creating scripts/src/sr_barbara_scripts/..."

# __init__.py — empty, marks the directory as a Python package
touch scripts/src/sr_barbara_scripts/__init__.py

# Placeholder files — actual content will be written separately
# Only create if they don't already exist
[ -f scripts/src/sr_barbara_scripts/pg_export.py ] || \
    touch scripts/src/sr_barbara_scripts/pg_export.py
[ -f scripts/src/sr_barbara_scripts/build_slingcode.py ] || \
    touch scripts/src/sr_barbara_scripts/build_slingcode.py

echo "      done."

# -----------------------------------------------------------------------------
# Step 5: Remove generated artifacts
# -----------------------------------------------------------------------------

echo "[5/7] Removing generated artifacts..."

# egg-info is always regenerated by pip install -e
[ -d sr_barbara.egg-info ] && rm -rf sr_barbara.egg-info

# __pycache__ should not be in the repo
find . -type d -name __pycache__ -not -path "./.git/*" -exec rm -rf {} + 2>/dev/null || true

echo "      done."

# -----------------------------------------------------------------------------
# Step 6: Archive old compose files if present
# -----------------------------------------------------------------------------

echo "[6/7] Checking archive/..."

[ -f archive/compose.yaml ] && mv archive/compose.yaml docs/archive/compose.yaml
[ -f archive/Dockerfile ]   && mv archive/Dockerfile   docs/archive/Dockerfile.archive
[ -d archive ] && rmdir archive 2>/dev/null || true

echo "      done."

# -----------------------------------------------------------------------------
# Step 7: Update .gitignore
# -----------------------------------------------------------------------------

echo "[7/7] Checking .gitignore..."

GITIGNORE=".gitignore"
ADDITIONS=(
    "# Environment files"
    ".env"
    ".env.dev"
    ""
    "# Generated artifacts"
    "*.egg-info/"
    "__pycache__/"
    "*.pyc"
    ""
    "# Build output — regenerated by srb-build"
    "# Remove this line if you want to commit dist/ for direct download"
    "dist/"
)

for LINE in "${ADDITIONS[@]}"; do
    if [ -n "$LINE" ] && grep -qF "$LINE" "$GITIGNORE" 2>/dev/null; then
        echo "      already in .gitignore: $LINE"
    else
        echo "$LINE" >> "$GITIGNORE"
    fi
done

echo "      done."

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------

echo ""
echo "Reorganization complete."
echo ""
echo "Next steps:"
echo "  1. Review changes with: git status"
echo "  2. Place sentences.yaml in data/"
echo "  3. Place pyproject.toml and sr_barbara.yaml at repo root"
echo "  4. Write scripts/src/sr_barbara_scripts/pg_export.py"
echo "  5. Write scripts/src/sr_barbara_scripts/build_slingcode.py"
echo "  6. Run: pip install -e scripts/"
echo "  7. Commit the reorganization as a single commit before making"
echo "     any other changes"
echo ""
echo "Files archived (not deleted) in docs/archive/:"
ls docs/archive/ 2>/dev/null || echo "  (none)"
